name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        buildozer_version: 'stable'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
        
